### ISSUE TITLE
조선민주주의인민공화국의 표준글쇠체계로의 변경 요청

### ISSUE THREAD

**Issue by kdhkr** [Alex4386/khexdump#2]
위대하신 **김정일**동지님께서는 콤퓨타 통신에 필요한 모든 매개물을 우리식으로 표현하라고 교시하시었다.
하지만, 이 《자식중앙》 웨브에 등록된 친남조선괴뢰도당 《저장소》는 남조선의 비과학적인 글쇠 체계를 따르고 있다.
따라서 본 《저장소》 관리자에게 본 매체의 《16진법 정렬 체계》를 다음과 같이 조선민주주의인민공화국의 《표준글쇠체계》에 맞추어 변경을 요청한다.
1 2 3 4 5 6 7 8 9 ㄱ ㄲ ㄴ ㄷ ㄸ

**Comment by Alex4386** [comment]
배포규정에 따라 본 체계는 개개인이 마음대로 복제 후 변경할 수 있다. 따라서 저장소를 복제한 후 사용하면 된다.  
변경을 원하는 경우, https://github.com/Alex4386/khexdump/blob/핵심/근원/기본.c#L19 를 수정하면 된다.  

변동 요청 닫음.

**Comment by kdhkr** [comment]
조선식 글쇠 표준이 세계적인 표준이 되어야하며, 이에 따라 남조선괴뢰도당의 비과학적인 글쇠 표준을 따르는 본 《저장소》의 내용을 수정하여야 할 것이다. 또한 이 《자식중앙》 웨브의 《저장소》를 관리하는 주인은 남조선괴뢰도당을 옹호하는 일련의 행위에 대하여 사과해야 할 것이다.
